apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "canasta-helm.fullname" . }}-database-backup
  namespace: {{ .Release.Namespace | quote }}
spec:
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - args:
            - {{ .Files.Glob "scripts/backup.sh" }}
            command:
            - "/bin/sh"
            image: {{ include "canasta.image" . | quote }}
            imagePullPolicy: IfNotPresent
            name: database-backup
            volumeMounts:
            - mountPath: /backups
              name: mysql-backup-volume
            - mountPath: /backup_scripts
              name: mysql-backup-scripts
          restartPolicy: OnFailure
          volumes:
          - hostPath:
              path: /opt/mediawiki/backups
              type: DirectoryOrCreate
            name: mysql-backup-volume
          - hostPath:
              path: /opt/mediawiki/backup_scripts
              type: Directory
            name: mysql-backup-scripts
  schedule: {{ .Values.cronjob.schedule }}