apiVersion: v1
kind: Service
metadata:
  name: {{ include "canasta-helm.fullname" . }}-db
  namespace: {{ .Release.Namespace | quote }}
  labels:
    io.kompose.service: db
  {{- include "canasta-helm.labels" . | nindent 4 }}
status:
  loadBalancer: {}
spec:
  selector:
    io.kompose.service: db
  ports:
	{{- .Values.db.ports | toYaml | nindent 2 -}}