apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "canasta-helm.fullname" . }}
spec:
  selector:
    matchLabels:
      app: canasta
  replicas: {{ .Values.image.replicaCount }}
  template:
    metadata:
      labels:
        app: canasta
    spec:
      containers:
      - name:  {{ include "canasta-helm.fullname" . }}-web
        image: {{ template "canasta.image" . }}
        resources: {}
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: canasta-env
        volumeMounts:
        - mountPath: /var/www/mediawiki/w/user-extensions
          name: config-volume
          subPath: ./extensions
        - mountPath: /var/www/mediawiki/w/user-skins
          name: config-volume
          subPath: ./skins
        - mountPath: /mediawiki/config
          name: canasta-config
        - mountPath: /mediawiki/config/settings
          name: canasta-settings
        - mountPath: /mediawiki/images
          name: config-volume
          subPath: ./images
        - name: sitemap-data
          mountPath: /mediawiki/sitemap
      - name: {{ include "canasta-helm.fullname" . }}-elasticsearch
        image: {{ .Values.elasticsearch.registry }}/{{ .Values.elasticsearch.repository }}:{{ .Values.elasticsearch.tag | default .Chart.AppVersion }}
        ports:
        - containerPort: 9200
        env:
        - name: discovery.type
          value: single-node
        - name: bootstrap.memory_lock
          value: "true"
        - name: ES_JAVA_OPTS
          value: "-Xms512m -Xmx512m"
        resources:
          requests:
            memory: {{ .Values.elasticsearch.memory }}
        volumeMounts:
        - mountPath: /usr/share/elasticsearch/data
          name: elasticsearch
        securityContext:
          capabilities:
            add:
              - IPC_LOCK
      volumes:
      - name: canasta-config
        configMap:
          name: canasta-config
      - name: canasta-settings
        configMap:
          name: canasta-settings
      - name: config-volume
        hostPath:
          path: /canasta/config-data
          type: DirectoryOrCreate
      - name: {{ tpl .Values.primary.persistence.existingClaim . }}
        persistentVolumeClaim:
          claimName: {{ tpl .Values.primary.persistence.existingClaim . }}
      - name: elasticsearch
        persistentVolumeClaim:
          claimName: {{ tpl .Values.secondary.persistence.existingClaim . }}