apiVersion: v1
kind: Service
metadata:
  name: {{ include "canasta-helm.fullname" . }}-elasticsearch
  namespace: {{ .Release.Namespace | quote }}
  labels:
    io.kompose.service: elasticsearch
status:
  loadBalancer: {}
spec:
  selector:
    io.kompose.service: elasticsearch
  ports:
	{{- .Values.elasticsearch.ports | toYaml | nindent 2 -}}