apiVersion: v1
kind: Secret
metadata:
  name: {{ include "canasta-helm.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    io.kompose.service: db
  {{- include "canasta-helm.labels" . | nindent 4 }}
type: Opaque
data:
  password: {{ .Values.externalDatabase.password | b64enc }}
