apiVersion: v1
kind: Service
metadata:
  name: {{ include "canasta-helm.fullname" . }}-web
  namespace: {{ .Release.Namespace | quote }}
  labels:
    io.kompose.service: web
status:
  loadBalancer: {}
spec:
  selector:
    io.kompose.service: web
  ports:
	{{- .Values.web.ports | toYaml | nindent 2 -}}