apiVersion: v2
appVersion: "0.1.0"
name: canasta
description: A Helm chart for Kubernetes
dependencies:
- name: common
  repository: https://charts.bitnami.com/bitnami
  tags:
  - bitnami-common
  version: 2.x.x

type: application
# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.1.0
description: This is a modified version of Canasta for Kubernetes that requires an external database and does not include Caddy or Varnish